//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.09 at 05:43:39 PM EET 
//


package com.jdevsul.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the goChat_JAXB package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ChatHistory_QNAME = new QName("", "chatHistory");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: goChat_JAXB
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link MessageFormat }
     * 
     */
    public MessageFormat createMessageFormat() {
        return new MessageFormat();
    }

    /**
     * Create an instance of {@link MessageDetails }
     * 
     */
    public MessageDetails createMessageDetails() {
        return new MessageDetails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Messages }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "chatHistory")
    public JAXBElement<Messages> createChatHistory(Messages value) {
        return new JAXBElement<Messages>(_ChatHistory_QNAME, Messages.class, null, value);
    }

}
